package $defaultPackageName$.service;

import $defaultPackageName$.domain.$entity.name$;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class $entity.name$ServiceImpl implements $entity.name$Service{

    private final Logger logger = LoggerFactory.getLogger($entity.name$ServiceImpl.class);

    public $entity.name$ get(String primaryKey) {
        return null;
    }

    public void save($entity.name$ $entity.nameLowerFirst$) {

    }

    public void save(final List<$entity.name$> $entity.pluralLowerFirst$) {

    }

    public void delete($entity.name$ $entity.nameLowerFirst$) {

    }

    public void delete(final List<$entity.name$> $entity.pluralLowerFirst$) {

    }
}
